### ISSUE TITLE
Blizcord on Raspbian Lite

### ISSUE THREAD

**Issue by enolp** [Bleuzen/Blizcord#8]
I'm unable to run Blizcord on Raspbian Lite (it has not any desktop environment) but is able to connect to Discord and stay online. However it doesn't do anything when you call it: 

[12:23:37] [INFO] [Blizcord] Version: 0.9.2
[12:23:37] [INFO] [Blizcord] Developer: Bleuzen <supgesu@gmail.com>
[12:23:37] [INFO] [Blizcord] Starting bot...
[12:23:37] [INFO] [Blizcord] Config: /home/user/.blizcord/config.json
[12:23:37] [INFO] [Blizcord] Starting JDA...
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.jnativehook.GlobalScreen.getAutoRepeatRate()Ljava/lang/Integer;
        at org.jnativehook.GlobalScreen.getAutoRepeatRate(Native Method)
        at org.jnativehook.GlobalScreen.<clinit>(Unknown Source)
        at com.github.bleuzen.blizcord.c.a(Unknown Source)
        at com.github.bleuzen.blizcord.a.d.h(Unknown Source)
        at com.github.bleuzen.blizcord.a.d.a(Unknown Source)
        at com.github.bleuzen.blizcord.a.main(Unknown Source)

And when I tried to call it to play a YouTube video, It threw me this error:

12:24:20.063 [JDA MainWS-ReadThread] ERROR net.dv8tion.jda.core.JDA - One of the EventListeners had an uncaught exception
java.lang.NullPointerException: null
        at java.lang.String.startsWith(String.java:1405)
        at java.lang.String.startsWith(String.java:1434)
        at com.github.bleuzen.blizcord.a.d.onMessageReceived(Unknown Source)
        at net.dv8tion.jda.core.hooks.ListenerAdapter.onEvent(Unknown Source)
        at net.dv8tion.jda.core.hooks.InterfacedEventManager.handle(Unknown Source)
        at net.dv8tion.jda.core.handle.MessageCreateHandler.handleInternally(Unknown Source)
        at net.dv8tion.jda.core.handle.SocketHandler.handle(Unknown Source)
        at net.dv8tion.jda.core.requests.WebSocketClient.onDispatch(Unknown Source)
        at net.dv8tion.jda.core.requests.WebSocketClient.onEvent(Unknown Source)
        at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(Unknown Source)
        at net.dv8tion.jda.core.requests.WebSocketClient.onBinaryMessage(Unknown Source)
        at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(Unknown Source)
        at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(Unknown Source)
        at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(Unknown Source)
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(Unknown Source)
        at com.neovisionaries.ws.client.ReadingThread.main(Unknown Source)
        at com.neovisionaries.ws.client.ReadingThread.runMain(Unknown Source)
        at com.neovisionaries.ws.client.WebSocketThread.run(Unknown Source)

**Comment by Bleuzen** [comment]
Yeah I guess this is because lavaplayer does not support arm.
I also tryed to run this on RPI some time ago but got similar problems.
Since the maintainer and developer of lavaplayer has no plans to support arm, Blizcord also won't support arm in the near future, sorry.

You can keep track of the lavaplayer request here:
https://github.com/sedmelluq/lavaplayer/issues/16

I know there is an arm version of the library that we need to get it working, but it is compiled by someone I don't know and:
1. Not sure if we get updates, so it could stop working at some point.
2. I don't like including some random binary files from an unknown person into my projects (security risk).

**Comment by enolp** [comment]
Bad news... Well, I hope he changes it's mind. I close this issue.
